[project]
name = "app_inventor_api"
version = "0.1.0"
description = "Add a short description here"
authors = ["CoolJosh0221 <joshluffy99@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-64", "osx-arm64", "linux-64"]

[tasks]

[dependencies]
fastapi = "0.103.2.*"
uvicorn = "0.23.2.*"
requests = "2.31.0.*"
icecream = "2.1.3.*"
